#!/usr/bin/python3

"""
This script calls the uncrusitfy for all the source files specified by user

Usage: ./script_name  (source code directory)
"""

import sys
import os
import subprocess
import shlex

# Global variables, used to filter source code file
fileappendix = (".cpp", ".c", ".cc", ".h")


def getSourceFiles(directory):
    for parent, dirnames, filenames in os.walk(directory):
        for filename in filenames:
            if filename.endswith(fileappendix):
                yield os.path.join(parent, filename)


# Iterate all the source file to and beautify it
def beautify_code(root_dir):
    for src in getSourceFiles(root_dir):
        if not os.path.isfile(src):
            continue
        command = "uncrustify -c uncrustify.cfg -f %s -o %s" % (src, src)
        print("Executing " + command)
        os.system(command)

        # Delete the temporal files generated by uncrustify
        tmpfile = src + ".unc-backup~ " + src + ".unc-backup.md5~ " + src + ".uncrustify"
        os.system("rm -f " + tmpfile)


if __name__ == "__main__":

# Default use the src directory
    source_code_dir = "../../src"

    if len(sys.argv) >= 2:
        source_code_dir = sys.argv[1]

    beautify_code(source_code_dir)
